CREATE DATABASE IF NOT EXISTS uts_pwl;
USE uts_pwl;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS buku (
    id INT AUTO_INCREMENT PRIMARY KEY,
    judul VARCHAR(150) NOT NULL,
    pengarang VARCHAR(120) NOT NULL,
    tahun YEAR NOT NULL,
    stok INT NOT NULL DEFAULT 0,
    status ENUM('Tersedia', 'Dipinjam') NOT NULL DEFAULT 'Tersedia',
    gambar VARCHAR(255) DEFAULT NULL,
    thumbpath VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (username, password)
SELECT 'admin', '$2y$10$2irH9hsFA01z6nNuoSMN6.Q6hufE0FcsmJLkTK4rLDRoMFhzsEpCu'
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE username = 'admin'
);
